name: 'Perform Test Coverage'
description: 'Runs tests, extracts coverage data, publishes it to NOCODB and Codecov server'
inputs:
  NOCODB_TOKEN:
    description: 'Token for NOCODB API authentication'
    required: true
  CODECOV_TOKEN:
    description: 'Token for Codecov API authentication'
    required: true
  REPO_NAME:
    description: 'Name of the repository'
    required: true
  BRANCH_NAME:
    description: 'Name of the branch'
    required: true
  COVERAGE_PERCENTAGE:
    description: 'normalizing the coverage percentage from 0 to 1'
    required: true
outputs: {}
runs:
  using: 'composite'
  steps:
   
    - name: Extract coverage data and publish to NOCODB
      run: |
        echo "start"
        

        # Construct JSON payload for NOCODB
        JSON_PAYLOAD="{\"repository\": \"${{ inputs.REPO_NAME }}\", \"branch\": \"${{ inputs.BRANCH_NAME }}\", \"coverage\": \"${{ inputs.COVERAGE_PERCENTAGE }}\"}"
        echo $JSON_PAYLOAD 

        # Send data to NOCODB API
        curl -v -k -X POST -H "xc-token: ${{ inputs.NOCODB_TOKEN }}" -H "Content-Type: application/json" -d "$JSON_PAYLOAD" https://nocodb.k8s.development.atacng.atacama.de/api/v2/tables/m6tnt0gaafb51hn/records
      shell: bash
      
      env:
        NOCODB_TOKEN: ${{ inputs.NOCODB_TOKEN }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ inputs.CODECOV_TOKEN }}
        
