name: 'Perform Test Coverage'
description: 'Runs tests, extracts coverage data, publishes it to NOCODB and Codecov server'
inputs:
  NOCODB_TOKEN:
    description: 'Token for NOCODB API authentication'
    required: true
  CODECOV_TOKEN:
    description: 'Token for Codecov API authentication'
    required: true
  REPO_NAME:
    description: 'Name of the repository'
    required: true
  BRANCH_NAME:
    description: 'Name of the branch'
    required: true
  COVERAGE_FILE_PATH:
    description: 'Path to the cobertura.xml'
    required: true
outputs: {}
runs:
  using: 'composite'
  steps:
   
    - name: Extract coverage data and publish to NOCODB
      run: |
        echo "start"
        pwd
        cat target/scala-2.13/scoverage-report/scoverage.xml
        cat target/scala-2.13/scoverage-report/scoverage.xml | grep -m1 -Po 'statement-rate="\K[^"]*'
        COVERAGE_PERCENTAGE=$(cat ${{ inputs.COVERAGE_FILE_PATH }} | grep -m1 -Po 'line-rate="\K[^"]*') 
        echo $COVERAGE_PERCENTAGE
        JSON_PAYLOAD="{\"repository\": \"${{ inputs.REPO_NAME }}\", \"branch\": \"${{ inputs.BRANCH_NAME }}\", \"coverage\": \"$COVERAGE_PERCENTAGE\"}"
        echo $JSON_PAYLOAD 
        curl -v -k -X POST -H "xc-token: ${{ inputs.NOCODB_TOKEN }}" -H "Content-Type: application/json" -d "$JSON_PAYLOAD" https://nocodb.k8s.development.atacng.atacama.de/api/v2/tables/m6tnt0gaafb51hn/records
      shell: bash
      
      env:
        NOCODB_TOKEN: ${{ inputs.NOCODB_TOKEN }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ inputs.CODECOV_TOKEN }}
        
