name: 'Perform Test Coverage'
description: 'Runs tests, extracts coverage data, publishes it to nocodb and Codecov server'
inputs: {}
outputs: {}
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

jobs:
  test-coverage:
    name: Perform test coverage
    env:
      SBT_OPTS: "-XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=2G -Xmx2G -Xms1G"
    runs-on: k8s-development-sbt-dind-runner-set
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Compile
      run: sbt compile

    - name: Testing
      run: sbt clean coverage test coverageReport

    - name: Extract coverage data and publish
      run: |
        REPO_NAME="${GITHUB_REPOSITORY}"
        BRANCH_NAME="${GITHUB_REF#refs/heads/}"
        COVERAGE_PERCENTAGE=$(cat target/scala-2.13/coverage-report/cobertura.xml | grep -m1 -Po 'line-rate="\K[^"]*') 
        NOCODB_TOKEN="${{ secrets.NOCODB_TOKEN }}"
        JSON_PAYLOAD="{\"repository\": \"$REPO_NAME\", \"branch\": \"$BRANCH_NAME\", \"coverage\": \"$COVERAGE_PERCENTAGE\"}"
        echo $JSON_PAYLOAD 
        curl -v -k -X POST  -H "xc-token: $NOCODB_TOKEN" -H "Content-Type: application/json" -d "$JSON_PAYLOAD" https://nocodb.k8s.development.atacng.atacama.de/api/v2/tables/m6tnt0gaafb51hn/records

      env:
        NOCODB_TOKEN: ${{ secrets.NOCODB_TOKEN }}

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: "**/cobertura.xml"
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
